import type { Metadata } from "next";
import "./globals.css";
import AuthContextProvider from "@/context/authContext";


export const metadata: Metadata = {
  title: "StayCation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className="bg-custom-gradient bg-no-repeat min-h-screen">
         <AuthContextProvider>
            {children}
         </AuthContextProvider>
      </body>
    </html>
  );
}
