import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "StayCation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className="bg-custom-gradient bg-no-repeat h-full">
        {children}
      </body>
    </html>
  );
}
